import type { Metadata } from "next";
import { Inter, Raleway, DM_Serif_Text } from "next/font/google";
import "./globals.css";

const dm_serif_text = DM_Serif_Text({
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={dm_serif_text.className}>{children}</body>
    </html>
  );
}
